spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://qq.com
          predicates:
            - Query=url,qq